require 'rake'
require 'rake/rdoctask'
# FIX: Hoe always calls rdoc with -d, and diagram generation fails here
class Rake::RDocTask
    alias __option_list__ option_list
    def option_list
	options = __option_list__
	options.delete("-d")
	options
    end
end

require 'hoe'
require './lib/simlog'

Hoe.new('pocosim-log', Pocosim::SIMLOG_VERSION) do |p|
    p.author = "Sylvain Joyeux"
    p.email = "sylvain.joyeux@laas.fr"

    p.summary = 'Manipulation library of binary log files generated by the pocosim robotics simulator'
    p.description = p.paragraphs_of('README.txt', 3..6).join("\n\n")
    p.url         = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
    p.changes     = p.paragraphs_of('Changes.txt', 0).join("\n\n")

    p.extra_deps << ['utilrb']
    p.extra_deps << ['genom']
    p.rdoc_pattern = /(ext\/.*cc$|lib)|txt/
end

