require 'rake'
require './lib/simlog/version'
require 'rdoc'

begin
    require 'hoe'
    Hoe.spec 'pocosim-log' do
        developer "Sylvain Joyeux", "sylvain.joyeux@m4x.org"

        self..summary = 'Manipulation library of binary log files generated by the pocosim robotics simulator'
        self..description = paragraphs_of('README.txt', 3..6).join("\n\n")
        self.url          = paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
        self.changes      = paragraphs_of('Changes.txt', 0).join("\n\n")

        extra_deps << ['utilrb', '>= 0.0']
    end
end

